spring.application.name=gateway
server.port=8080

# Configuración JWT (debe ser idéntica al microservicio usuarios)
bezkoder.app.jwtSecret=U2kgdmlzIHBhY2VtLCBwYXJhIGJlbGx1bSBNZW1lbnRvIG1vcmk=
bezkoder.app.jwtExpirationMs=3600000

## Configuración de CORS
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-origins=http://localhost:5173
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-methods=GET,POST,PUT,DELETE,OPTIONS
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allowed-headers=*
#spring.cloud.gateway.globalcors.cors-configurations.[/**].allow-credentials=true

# Logging
logging.level.org.springframework.cloud.gateway=DEBUG
logging.level.co.edu.unicauca.gateway=DEBUG
logging.level.reactor.netty=DEBUG

# Configuración para evitar errores de timeout
spring.cloud.gateway.httpclient.connect-timeout=1000
spring.cloud.gateway.httpclient.response-timeout=5s

# Configuración para discovery (si usas Eureka en el futuro)
# spring.cloud.gateway.discovery.locator.enabled=true
# spring.cloud.gateway.discovery.locator.lower-case-service-id=true 